@echo off
echo Starting Projectile Motion Simulator...
echo Installing dependencies if needed...
pip install -q -r requirements.txt

echo Launching application...
python projectile_simulator.py
pause
